/**
 * Mock Data for Landing Page Preview
 * Sample room analysis to showcase the report functionality
 */

import type { EnhancedAnalysisResponse, RoomProject } from "@/app/types/room"

export const mockProject: RoomProject = {
  goal: "music",
  lengthM: 4.5,
  widthM: 3.8,
  heightM: 2.7,
  floorType: "madera",
  wallType: "desnudas",
  hasCarpet: false,
  hasCurtains: false,
  furniture: ["sofa", "escritorio", "estanteria"],
  speakerConfig: "stereo",
  listeningPosition: "centro",
}

export const mockAnalysis: EnhancedAnalysisResponse = {
  summary:
    "Tu espacio presenta características de sala VIVA con reverberación alta en frecuencias medias-altas. Los modos de sala más problemáticos están en 38Hz, 45Hz y 76Hz. Se recomienda priorizar absorción en primeros reflejos y trampas de graves en esquinas.",
  roomCharacter: "viva",
  priorityScore: {
    critical: 2,
    improvements: 4,
    optimizations: 3,
  },
  roomMetrics: {
    volume: 46.17,
    surfaceArea: 85.86,
    floorArea: 17.1,
    wallArea: 55.8,
    ceilingArea: 17.1,
    ratios: {
      lengthWidth: 1.18,
      lengthHeight: 1.67,
      widthHeight: 1.41,
    },
    roomModes: [
      {
        frequency: 38.1,
        type: "axial",
        dimension: "length",
        severity: "high",
        description: "1° modo longitudinal (4.5m)",
      },
      {
        frequency: 45.1,
        type: "axial",
        dimension: "width",
        severity: "high",
        description: "1° modo transversal (3.8m)",
      },
      {
        frequency: 63.5,
        type: "axial",
        dimension: "height",
        severity: "medium",
        description: "1° modo vertical (2.7m)",
      },
      {
        frequency: 76.2,
        type: "axial",
        dimension: "length",
        severity: "medium",
        description: "2° modo longitudinal (4.5m)",
      },
      {
        frequency: 90.3,
        type: "axial",
        dimension: "width",
        severity: "medium",
        description: "2° modo transversal (3.8m)",
      },
    ],
    rt60Estimate: {
      low: 0.68,
      mid: 0.52,
      high: 0.38,
    },
    totalAbsorption: 12.5,
  },
  frequencyResponse: [
    { frequency: 30, response: 0, issue: false },
    { frequency: 40, response: 6, issue: true, description: "Modo axial fuerte" },
    { frequency: 50, response: 3, issue: false },
    { frequency: 63, response: 4, issue: true, description: "Resonancia altura" },
    { frequency: 80, response: 5, issue: true, description: "Acumulación graves" },
    { frequency: 100, response: 2, issue: false },
    { frequency: 125, response: 1, issue: false },
    { frequency: 160, response: 0, issue: false },
    { frequency: 200, response: -1, issue: false },
    { frequency: 250, response: 0, issue: false },
    { frequency: 315, response: 1, issue: false },
    { frequency: 400, response: 2, issue: false },
    { frequency: 500, response: 3, issue: false },
    { frequency: 630, response: 2, issue: false },
    { frequency: 800, response: 1, issue: false },
    { frequency: 1000, response: 0, issue: false },
  ],
  freeChanges: {
    title: "Cambios Gratuitos (Esta Semana)",
    items: [
      "Mover punto de escucha al 38% de la profundidad (1.7m desde pared frontal)",
      "Agregar alfombras gruesas o mantas en el centro del piso",
      "Colgar cortinas pesadas o mantas en ventanas",
      "Reorganizar estantería con libros de diferentes tamaños para difusión",
      "Alejar parlantes de paredes y esquinas (mínimo 50cm)",
    ],
  },
  lowBudgetChanges: {
    title: "Mejoras Bajo Presupuesto ($50k - $150k ARS)",
    totalEstimatedCost: {
      min: 52000,
      max: 148000,
      currency: "ARS",
    },
    items: [
      {
        category: "Absorción",
        product: "Panel Espuma Acústica 60x60cm (5cm)",
        quantity: 8,
        unitPrice: 6500,
        totalPrice: 52000,
        supplier: "MercadoLibre",
        link: "https://mercadolibre.com.ar/...",
        placement: "First reflection points (paredes laterales)",
        impactLevel: "high",
        installation: "easy",
      },
      {
        category: "Graves",
        product: "Trampa de Graves Esquina Básica",
        quantity: 4,
        unitPrice: 12000,
        totalPrice: 48000,
        supplier: "MercadoLibre",
        link: "https://mercadolibre.com.ar/...",
        placement: "4 esquinas verticales",
        impactLevel: "high",
        installation: "moderate",
      },
      {
        category: "Piso",
        product: "Alfombra Gruesa 2x3m",
        quantity: 1,
        unitPrice: 48000,
        totalPrice: 48000,
        supplier: "Local / IKEA",
        link: "",
        placement: "Centro de sala bajo punto de escucha",
        impactLevel: "medium",
        installation: "easy",
      },
    ],
  },
  advancedChanges: {
    title: "Tratamiento Avanzado ($150k - $400k ARS)",
    totalEstimatedCost: {
      min: 170000,
      max: 380000,
      currency: "ARS",
    },
    items: [
      {
        category: "Absorción Pro",
        product: "Panel Acústico Profesional 60x120cm (10cm)",
        quantity: 6,
        unitPrice: 34000,
        totalPrice: 204000,
        supplier: "GIK Acoustics / Local",
        link: "",
        placement: "First reflection points + techo",
        impactLevel: "high",
        installation: "moderate",
      },
      {
        category: "Difusión",
        product: "Difusor QRD 60x60cm",
        quantity: 2,
        unitPrice: 38000,
        totalPrice: 76000,
        supplier: "Acoustics First",
        link: "",
        placement: "Pared trasera",
        impactLevel: "medium",
        installation: "moderate",
      },
      {
        category: "Graves Pro",
        product: "Trampa de Graves Profesional Esquina",
        quantity: 2,
        unitPrice: 48000,
        totalPrice: 96000,
        supplier: "GIK Acoustics",
        link: "",
        placement: "Esquinas frontales",
        impactLevel: "high",
        installation: "professional",
      },
    ],
  },
  roomDiagram: {
    floorPlan: {
      width: 3.8,
      length: 4.5,
      speakerPositions: [
        { x: 0.21, y: 0.22 },
        { x: 0.79, y: 0.22 },
      ],
      listeningPosition: { x: 0.50, y: 0.60 },
      furnitureLayout: [
        { type: "sofa", x: 0.39, y: 0.78, width: 0.47, length: 0.20 },
        { type: "escritorio", x: 0.05, y: 0.04, width: 0.32, length: 0.13 },
        { type: "estanteria", x: 0.92, y: 0.22, width: 0.08, length: 0.44 },
      ],
    },
    treatmentPlan: [
      {
        type: "absorber",
        position: { x: 0, y: 0.44 },
        wall: "left",
        priority: "high",
      },
      {
        type: "absorber",
        position: { x: 1, y: 0.44 },
        wall: "right",
        priority: "high",
      },
      {
        type: "bass_trap",
        position: { x: 0, y: 0 },
        wall: "front",
        priority: "high",
      },
      {
        type: "bass_trap",
        position: { x: 1, y: 0 },
        wall: "front",
        priority: "high",
      },
    ],
  },
  generatedAt: new Date().toISOString(),
}
